# If you wish to use your own resource pack, disable the pack here and merge https://github.com/cometcake575/WaypointHomes/raw/refs/heads/main/WaypointPack.zip with your own pack
enable-resource-pack: true

# Do not touch this!
config-version: 1.0.0
